# Generated by Django 4.1.5 on 2023-02-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customerdetails_delete_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
