# Generated by Django 4.1.5 on 2023-01-03 15:35

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.TextField()),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=200)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(default='India', max_length=100)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchase_id', models.CharField(blank=True, max_length=200, null=True)),
                ('order_status', models.CharField(default='Ordered', max_length=100)),
                ('order_tracking', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('colors', models.TextField(blank=True, null=True)),
                ('photo1', models.FileField(blank=True, null=True, upload_to=products.models.product_image)),
                ('photo2', models.FileField(blank=True, null=True, upload_to=products.models.product_image)),
                ('photo3', models.FileField(blank=True, null=True, upload_to=products.models.product_image)),
                ('photo4', models.FileField(blank=True, null=True, upload_to=products.models.product_image)),
                ('photo5', models.FileField(blank=True, null=True, upload_to=products.models.product_image)),
                ('photo6', models.FileField(blank=True, null=True, upload_to=products.models.product_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
