# Generated by Django 4.1.5 on 2023-01-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_active_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='printable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
