# Generated by Django 4.1.5 on 2023-02-09 15:45

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_printable_alter_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to=products.models.invoice_file),
        ),
        migrations.AddField(
            model_name='order',
            name='track_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
