# Generated by Django 4.1.5 on 2023-02-15 15:41

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='printableFile',
            field=models.FileField(blank=True, null=True, upload_to=products.models.printable_file),
        ),
    ]
