# Generated by Django 4.1.5 on 2023-04-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_order_printablefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Unpaid', max_length=100),
        ),
    ]
